<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<UseAppHost>true</UseAppHost>
		<RootNamespace>smartboy_dumper</RootNamespace>
		<AssemblyName>smartboy-dumper</AssemblyName>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
</Project>